[package]
name = "dragnload"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
actix-web = "4"
tokio = { version = "1", features = ["full"] }
actix-multipart = "0.6.2"
local-ip-address = "0.6.1"